---
name_public: dns1
name_intern: res3
name_other_public: dns2
name_other_intern: res4
ip4: "{{ ip4_dns1 }}"
ip6: "{{ ip6_dns1 }}"
ip4_other: "{{ ip4_dns2 }}"
ip6_other: "{{ ip6_dns2 }}"
vrrp_prio_42: 200
vrrp_prio_43: 100
