---
- name: Setup Webserver
  tags: webserver
  block:
    - import_tasks: nginx.yml
    - import_tasks: letsencrypt.yml
      when: inventory_hostname in groups["prod"]
    - import_tasks: localencrypt.yml
      when: inventory_hostname in groups["local"]
