---
- name: Software | install utility packages
  ansible.builtin.package:
    state: present
    name:
      - curl
      - dnsutils
      - git
      - htop
      - iputils-ping
      - knot-dnsutils
      - net-tools
      - netcat-openbsd
      - openssh-client
      - openssl
      - rsync
      - tcpdump
      - telnet
      - traceroute
      - tree
      - vim
      - wget
      - whois
