dnsdist_control_interface_key: "KZ0-+U?T"
dnsdist_webserver_api_key: "K[F|8I9?"
dnsdist_webserver_password: "Lj9*kN?Z"
keepalived_dns42_4: "tT,'f'?R"
keepalived_dns42_6: "1}[&Is>x"
keepalived_dns43_4: "`B<VDz?p"
keepalived_dns43_6: "3+=rnF8="
statisitcs_user: statisticsUser
statistics_password: "PBawJ~^Q"
