---
- name: firewall | install software
  ansible.builtin.package:
    state: latest
    name:
      - iptables
      - nftables

- name: firewall | uninstall software
  ansible.builtin.package:
    state: absent
    name:
      - iptables-persistent
      - netfilter-persistent
      - ufw

# Load firewall connection tracking kernel modules and reconnect.

- name: firewall | load kernel modules
  community.general.modprobe:
    name: xt_conntrack

- name: firewall | reset connection
  ansible.builtin.meta: reset_connection
- name: firewall | cleanup
  ansible.builtin.file:
    state: absent
    path: /etc/iptables

- name: firewall | rules
  notify:
    - firewall | apply ruleset
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    validate: /usr/sbin/nft --check --file %s
    owner: root
    group: root
    mode: "0644"

- name: firewall | enabled
  ansible.builtin.service:
    name: nftables
    state: started
    enabled: true
