---
- name: firewall | install software
  package:
    state: latest
    name:
      - iptables
      - nftables

- name: firewall | uninstall software
  package:
    state: absent
    name:
      - iptables-persistent
      - netfilter-persistent
      - ufw

# Load firewall connection tracking kernel modules and reconnect.

- name: firewall | load kernel modules
  modprobe:
    name: xt_conntrack

- name: firewall | reset connection
  meta: reset_connection

- name: firewall | cleanup
  file:
    state: absent
    path: /etc/iptables

- name: firewall | rules
  notify:
    - firewall | apply ruleset
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    validate: /usr/sbin/nft --check --file %s
    owner: root
    group: root
    mode: 0644

- name: firewall | enabled
  service:
    name: nftables
    state: started
    enabled: true
