---
- name: Setup OS
  tags: base
  block:
    - name: Setup Network
      ansible.builtin.import_tasks: network.yml
      tags: network,init

    - name: Setup Users
      tags: init
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - users/*.yml

    - name: Setup Software
      tags: init
      block:
        - name: Setup unattended-upgrades
          ansible.builtin.import_tasks: unattended-upgrades.yml
        - name: Cleanup packages
          ansible.builtin.import_tasks: software/packages_cleanup.yml
        - name: Setup utilities
          ansible.builtin.import_tasks: software/packages_utilities.yml

    - name: Setup Firewall
      ansible.builtin.import_tasks: firewall.yml
      tags: firewall

    - name: Setup SSH
      tags: ssh,init
      ansible.builtin.import_tasks: sshd.yml
