---
- name: unattended-upgrades | install
  ansible.builtin.package:
    state: latest
    name: unattended-upgrades

- name: unattended-upgrades | ensure service is enabled and running
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true
