---
- name: Setup DNS Frontend
  tags: frontend
  block:
    - name: Setup PowerDNS repo
      ansible.builtin.import_tasks: powerdns-repo.yml
    - name: Setup dnsdist
      ansible.builtin.import_tasks: dnsdist.yml
