---
- name: PowerDNS repo | pinning
  ansible.builtin.copy:
    src: dnsdist.pref
    dest: /etc/apt/preferences.d/dnsdist.pref
    owner: root
    group: root
    mode: "0644"

- name: PowerDNS repo | keyring
  ansible.builtin.copy:
    src: FD380FBB-pub.asc
    dest: /etc/apt/keyrings/FD380FBB-pub.asc
    owner: root
    group: root
    mode: "0644"

- name: PowerDNS repo | sources
  ansible.builtin.copy:
    src: dnsdist.sources
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: "0644"

- name: PowerDNS repo | apt cache up-to-date
  ansible.builtin.apt:
    update_cache: true
