---
- name: Setup Metrics
  tags: metrics
  block:
    - name: Setup Prometheus
      ansible.builtin.import_tasks: prometheus-server.yml

    - name: Setup Node Exporter
      ansible.builtin.import_tasks: node-exporter.yml
