---
- name: restart ssh.socket
  when: ssh_socket_is_active.rc == 0
  ansible.builtin.systemd_service:
    name: ssh.socket
    state: restarted
    daemon_reload: true

- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: firewall | apply ruleset
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded

- name: apply netplan
  ansible.builtin.command: sudo netplan apply
  async: 45
  poll: 0
