---
- name: Restart ssh.socket
  when: base_ssh_socket_is_active.rc == 0
  ansible.builtin.systemd_service:
    name: ssh.socket
    state: restarted
    daemon_reload: true

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Firewall | apply ruleset
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded

- name: Apply netplan
  async: 45
  poll: 0
  changed_when: true
  ansible.builtin.command: sudo netplan apply
