---
- name: keepalived | install
  package:
    state: latest
    name: keepalived

- name: keepalived | ensure keepalived is started
  service:
    name: keepalived
    state: started

- name: keepalived | generate config file from template
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload keepalived
