---
- name: Setup DNS Backend
  tags: backend
  block:
    - name: Setup unbound
      ansible.builtin.import_tasks: unbound.yml
    - name: Disable systemd-resolved
      ansible.builtin.import_tasks: systemd-resolved.yml
