---
- name: unbound | install
  package:
    state: latest
    name: unbound

- name: unbound | increase socket buffer size
  loop:
    - rmem_max
    - wmem_max
  sysctl:
    name: "net.core.{{ item }}"
    value: '8388608'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-socket-buffer-size.conf
    state: present
    reload: true

- name: unbound | started
  service:
    name: unbound
    state: started

- name: unbound | control key present
  command:
    argv:
      - /usr/sbin/unbound-control-setup
    creates: /etc/unbound/unbound_server.pem

- name: unbound | generate config file from template
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: unbound
    mode: "0644"
  notify:
    - restart unbound
