name: Run lint

# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-26.04

    steps:
      - name: Check out project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run ansible-lint
        uses: ansible/ansible-lint@e7f397ad6dfa20d274afa17cd7bbedd84ed136f5 # v26.9.0
        with:
          requirements_file: "requirements.yml"
          working_directory: "configuration-files"
