name: Verify project

on:
  pull_request:
    branches: ["main"]
  push:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Check project formating
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .
